export interface Country {
  name: string;
  dial?: string;
  code?: string;
  emoji?: string;
  flag?: string;
}

const FLAG_STYLE = 'flat';
const FLAG_SIZE = '64';

const getFlagUrl = (countryCode: string) =>
  `https://flagsapi.com/${countryCode}/${FLAG_STYLE}/${FLAG_SIZE}.png`;

export const COUNTRIES: Country[] = [
  { name: 'United States', dial: '+1', code: 'US', emoji: '🇺🇸' },
  { name: 'Canada', dial: '+1', code: 'CA', emoji: '🇨🇦' },
  { name: 'Russia', dial: '+7', code: 'RU', emoji: '🇷🇺' },
  { name: 'Egypt', dial: '+20', code: 'EG', emoji: '🇪🇬' },
  { name: 'South Africa', dial: '+27', code: 'ZA', emoji: '🇿🇦' },
  { name: 'Greece', dial: '+30', code: 'GR', emoji: '🇬🇷' },
  { name: 'Netherlands', dial: '+31', code: 'NL', emoji: '🇳🇱' },
  { name: 'Belgium', dial: '+32', code: 'BE', emoji: '🇧🇪' },
  { name: 'France', dial: '+33', code: 'FR', emoji: '🇫🇷' },
  { name: 'Spain', dial: '+34', code: 'ES', emoji: '🇪🇸' },
  { name: 'Hungary', dial: '+36', code: 'HU', emoji: '🇭🇺' },
  { name: 'Italy', dial: '+39', code: 'IT', emoji: '🇮🇹' },
  { name: 'Romania', dial: '+40', code: 'RO', emoji: '🇷🇴' },
  { name: 'Switzerland', dial: '+41', code: 'CH', emoji: '🇨🇭' },
  { name: 'Austria', dial: '+43', code: 'AT', emoji: '🇦🇹' },
  { name: 'United Kingdom', dial: '+44', code: 'GB', emoji: '🇬🇧' },
  { name: 'Denmark', dial: '+45', code: 'DK', emoji: '🇩🇰' },
  { name: 'Sweden', dial: '+46', code: 'SE', emoji: '🇸🇪' },
  { name: 'Norway', dial: '+47', code: 'NO', emoji: '🇳🇴' },
  { name: 'Poland', dial: '+48', code: 'PL', emoji: '🇵🇱' },
  { name:- 'Germany', dial: '+49', code: 'DE', emoji: '🇩🇪' },
  { name: 'Peru', dial: '+51', code: 'PE', emoji: '🇵🇪' },
  { name: 'Mexico', dial: '+52', code: 'MX', emoji: '🇲🇽' },
  { name: 'Cuba', dial: '+53', code: 'CU', emoji: '🇨🇺' },
  { name: 'Argentina', dial: '+54', code: 'AR', emoji: '🇦🇷' },
  { name: 'Brazil', dial: '+55', code: 'BR', emoji: '🇧🇷' },
  { name: 'Chile', dial: '+56', code: 'CL', emoji: '🇨🇱' },
  { name: 'Colombia', dial: '+57', code: 'CO', emoji: '🇨🇴' },
  { name: 'Venezuela', dial: '+58', code: 'VE', emoji: '🇻🇪' },
  { name: 'Malaysia', dial: '+60', code: 'MY', emoji: '🇲🇾' },
  { name: 'Australia', dial: '+61', code: 'AU', emoji: '🇦🇺' },
  { name: 'Indonesia', dial: '+62', code: 'ID', emoji: '🇮🇩' },
  { name: 'Philippines', dial: '+63', code: 'PH', emoji: '🇵🇭' },
  { name: 'New Zealand', dial: '+64', code: 'NZ', emoji: '🇳🇿' },
  { name: 'Singapore', dial: '+65', code: 'SG', emoji: '🇸🇬' },
  { name: 'Thailand', dial: '+66', code: 'TH', emoji: '🇹🇭' },
  { name: 'Japan', dial: '+81', code: 'JP', emoji: '🇯🇵' },
  { name: 'South Korea', dial: '+82', code: 'KR', emoji: '🇰🇷' },
  { name: 'Vietnam', dial: '+84', code: 'VN', emoji: '🇻🇳' },
  { name: 'China', dial: '+86', code: 'CN', emoji: '🇨🇳' },
  { name: 'Turkey', dial: '+90', code: 'TR', emoji: '🇹🇷' },
  { name: 'India', dial: '+91', code: 'IN', emoji: '🇮🇳' },
  { name: 'Pakistan', dial: '+92', code: 'PK', emoji: '🇵🇰' },
  { name: 'Afghanistan', dial: '+93', code: 'AF', emoji: '🇦🇫' },
  { name: 'Sri Lanka', dial: '+94', code: 'LK', emoji: '🇱🇰' },
  { name: 'Myanmar', dial: '+95', code: 'MM', emoji: '🇲🇲' },
  { name: 'Iran', dial: '+98', code: 'IR', emoji: '🇮🇷' },
  { name: 'Morocco', dial: '+212', code: 'MA', emoji: '🇲🇦' },
  { name: 'Algeria', dial: '+213', code: 'DZ', emoji: '🇩🇿' },
  { name: 'Tunisia', dial: '+216', code: 'TN', emoji: '🇹🇳' },
  { name: 'Libya', dial: '+218', code: 'LY', emoji: '🇱🇾' },
  { name: 'Gambia', dial: '+220', code: 'GM', emoji: '🇬🇲' },
  { name: 'Senegal', dial: '+221', code: 'SN', emoji: '🇸🇳' },
  { name: 'Mauritania', dial: '+222', code: 'MR', emoji: '🇲🇷' },
  { name: 'Mali', dial: '+223', code: 'ML', emoji: '🇲🇱' },
  { name: 'Guinea', dial: '+224', code: 'GN', emoji: '🇬🇳' },
  { name: 'Ivory Coast', dial: '+225', code: 'CI', emoji: '🇨🇮' },
  { name: 'Burkina Faso', dial: '+226', code: 'BF', emoji: '🇧🇫' },
  { name: 'Niger', dial: '+227', code: 'NE', emoji: '🇳🇪' },
  { name: 'Togo', dial: '+228', code: 'TG', emoji: '🇹🇬' },
  { name: 'Benin', dial: '+229', code: 'BJ', emoji: '🇧🇯' },
  { name: 'Mauritius', dial: '+230', code: 'MU', emoji: '🇲🇺' },
  { name: 'Liberia', dial: '+231', code: 'LR', emoji: '🇱🇷' },
  { name: 'Sierra Leone', dial: '+232', code: 'SL', emoji: '🇸🇱' },
  { name: 'Ghana', dial: '+233', code: 'GH', emoji: '🇬🇭' },
  { name: 'Nigeria', dial: '+234', code: 'NG', emoji: '🇳🇬' },
  { name: 'Chad', dial: '+235', code: 'TD', emoji: '🇹🇩' },
  { name: 'Central African Republic', dial: '+236', code: 'CF', emoji: '🇨🇫' },
  { name: 'Cameroon', dial: '+237', code: 'CM', emoji: '🇨🇲' },
  { name: 'Cape Verde', dial: '+238', code: 'CV', emoji: '🇨🇻' },
  { name: 'Sao Tome and Principe', dial: '+239', code: 'ST', emoji: '🇸🇹' },
  { name: 'Equatorial Guinea', dial: '+240', code: 'GQ', emoji: '🇬🇶' },
  { name: 'Gabon', dial: '+241', code: 'GA', emoji: '🇬🇦' },
  { name: 'Congo', dial: '+242', code: 'CG', emoji: '🇨🇬' },
  { name: 'DR Congo', dial: '+243', code: 'CD', emoji: '🇨🇩' },
  { name: 'Angola', dial: '+244', code: 'AO', emoji: '🇦🇴' },
  { name: 'Guinea-Bissau', dial: '+245', code: 'GW', emoji: '🇬🇼' },
  { name: 'Seychelles', dial: '+248', code: 'SC', emoji: '🇸🇨' },
  { name: 'Sudan', dial: '+249', code: 'SD', emoji: '🇸🇩' },
  { name: 'Rwanda', dial: '+250', code: 'RW', emoji: '🇷🇼' },
  { name: 'Ethiopia', dial: '+251', code: 'ET', emoji: '🇪🇹' },
  { name: 'Somalia', dial: '+252', code: 'SO', emoji: '🇸🇴' },
  { name: 'Djibouti', dial: '+253', code: 'DJ', emoji: '🇩🇯' },
  { name: 'Kenya', dial: '+254', code: 'KE', emoji: '🇰🇪' },
  { name: 'Tanzania', dial: '+255', code: 'TZ', emoji: '🇹🇿' },
  { name: 'Uganda', dial: '+256', code: 'UG', emoji: '🇺🇬' },
  { name: 'Burundi', dial: '+257', code: 'BI', emoji: '🇧🇮' },
  { name: 'Mozambique', dial: '+258', code: 'MZ', emoji: '🇲🇿' },
  { name: 'Zambia', dial: '+260', code: 'ZM', emoji: '🇿🇲' },
  { name: 'Madagascar', dial: '+261', code: 'MG', emoji: '🇲🇬' },
  { name: 'Zimbabwe', dial: '+263', code: 'ZW', emoji: '🇿🇼' },
  { name: 'Namibia', dial: '+264', code: 'NA', emoji: '🇳🇦' },
  { name: 'Malawi', dial: '+265', code: 'MW', emoji: '🇲🇼' },
  { name: 'Lesotho', dial: '+266', code: 'LS', emoji: '🇱🇸' },
  { name: 'Botswana', dial: '+267', code: 'BW', emoji: '🇧🇼' },
  { name: 'Eswatini', dial: '+268', code: 'SZ', emoji: '🇸🇿' },
  { name: 'Comoros', dial: '+269', code: 'KM', emoji: '🇰🇲' },
  { name: 'Eritrea', dial: '+291', code: 'ER', emoji: '🇪🇷' },
  { name: 'Aruba', dial: '+297', code: 'AW', emoji: '🇦🇼' },
  { name: 'Faroe Islands', dial: '+298', code: 'FO', emoji: '🇫🇴' },
  { name: 'Greenland', dial: '+299', code: 'GL', emoji: '🇬🇱' },
  { name: 'Gibraltar', dial: '+350', code: 'GI', emoji: '🇬🇮' },
  { name: 'Portugal', dial: '+351', code: 'PT', emoji: '🇵🇹' },
  { name: 'Luxembourg', dial: '+352', code: 'LU', emoji: '🇱🇺' },
  { name: 'Ireland', dial: '+353', code: 'IE', emoji: '🇮🇪' },
  { name: 'Iceland', dial: '+354', code: 'IS', emoji: '🇮🇸' },
  { name: 'Albania', dial: '+355', code: 'AL', emoji: '🇦🇱' },
  { name: 'Malta', dial: '+356', code: 'MT', emoji: '🇲🇹' },
  { name: 'Cyprus', dial: '+357', code: 'CY', emoji: '🇨🇾' },
  { name: 'Finland', dial: '+358', code: 'FI', emoji: '🇫🇮' },
  { name: 'Bulgaria', dial: '+359', code: 'BG', emoji: '🇧🇬' },
  { name: 'Lithuania', dial: '+370', code: 'LT', emoji: '🇱🇹' },
  { name: 'Latvia', dial: '+371', code: 'LV', emoji: '🇱🇻' },
  { name: 'Estonia', dial: '+372', code: 'EE', emoji: '🇪🇪' },
  { name: 'Moldova', dial: '+373', code: 'MD', emoji: '🇲🇩' },
  { name: 'Armenia', dial: '+374', code: 'AM', emoji: '🇦🇲' },
  { name: 'Belarus', dial: '+375', code: 'BY', emoji: '🇧🇾' },
  { name: 'Andorra', dial: '+376', code: 'AD', emoji: '🇦🇩' },
  { name: 'Monaco', dial: '+377', code: 'MC', emoji: '🇲🇨' },
  { name: 'San Marino', dial: '+378', code: 'SM', emoji: '🇸🇲' },
  { name: 'Vatican City', dial: '+379', code: 'VA', emoji: '🇻🇦' },
  { name: 'Ukraine', dial: '+380', code: 'UA', emoji: '🇺🇦' },
  { name: 'Serbia', dial: '+381', code: 'RS', emoji: '🇷🇸' },
  { name: 'Montenegro', dial: '+382', code: 'ME', emoji: '🇲🇪' },
  { name: 'Croatia', dial: '+385', code: 'HR', emoji: '🇭🇷' },
  { name: 'Slovenia', dial: '+386', code: 'SI', emoji: '🇸🇮' },
  { name: 'Bosnia and Herzegovina', dial: '+387', code: 'BA', emoji: '🇧🇦' },
  { name: 'North Macedonia', dial: '+389', code: 'MK', emoji: '🇲🇰' },
  { name: 'Czech Republic', dial: '+420', code: 'CZ', emoji: '🇨🇿' },
  { name: 'Slovakia', dial: '+421', code: 'SK', emoji: '🇸🇰' },
  { name: 'Liechtenstein', dial: '+423', code: 'LI', emoji: '🇱🇮' },
  { name: 'Falkland Islands', dial: '+500', code: 'FK', emoji: '🇫🇰' },
  { name: 'Belize', dial: '+501', code: 'BZ', emoji: '🇧🇿' },
  { name: 'Guatemala', dial: '+502', code: 'GT', emoji: '🇬🇹' },
  { name: 'El Salvador', dial: '+503', code: 'SV', emoji: '🇸🇻' },
  { name: 'Honduras', dial: '+504', code: 'HN', emoji: '🇭🇳' },
  { name: 'Nicaragua', dial: '+505', code: 'NI', emoji: '🇳🇮' },
  { name: 'Costa Rica', dial: '+506', code: 'CR', emoji: '🇨🇷' },
  { name: 'Panama', dial: '+507', code: 'PA', emoji: '🇵🇦' },
  { name: 'Haiti', dial: '+509', code: 'HT', emoji: '🇭🇹' },
  { name: 'Bolivia', dial: '+591', code: 'BO', emoji: '🇧🇴' },
  { name: 'Ecuador', dial: '+593', code: 'EC', emoji: '🇪🇨' },
  { name: 'Paraguay', dial: '+595', code: 'PY', emoji: '🇵🇾' },
  { name: 'Uruguay', dial: '+598', code: 'UY', emoji: '🇺🇾' },
  { name: 'Guyana', dial: '+592', code: 'GY', emoji: '🇬🇾' },
  { name: 'Suriname', dial: '+597', code: 'SR', emoji: '🇸🇷' },
  { name: 'French Guiana', dial: '+594', code: 'GF', emoji: '🇬🇫' },
  { name: 'Brunei', dial: '+673', code: 'BN', emoji: '🇧🇳' },
  { name: 'Nauru', dial: '+674', code: 'NR', emoji: '🇳🇷' },
  { name: 'Papua New Guinea', dial: '+675', code: 'PG', emoji: '🇵🇬' },
  { name: 'Tonga', dial: '+676', code: 'TO', emoji: '🇹🇴' },
  { name: 'Solomon Islands', dial: '+677', code: 'SB', emoji: '🇸🇧' },
  { name: 'Vanuatu', dial: '+678', code: 'VU', emoji: '🇻🇺' },
  { name: 'Fiji', dial: '+679', code: 'FJ', emoji: '🇫🇯' },
  { name: 'Palau', dial: '+680', code: 'PW', emoji: '🇵🇼' },
  { name: 'Cook Islands', dial: '+682', code: 'CK', emoji: '🇨🇰' },
  { name: 'Samoa', dial: '+685', code: 'WS', emoji: '🇼🇸' },
  { name: 'Kiribati', dial: '+686', code: 'KI', emoji: '🇰🇮' },
  { name: 'Tuvalu', dial: '+688', code: 'TV', emoji: '🇹🇻' },
  { name: 'Marshall Islands', dial: '+692', code: 'MH', emoji: '🇲🇭' },
  { name: 'North Korea', dial: '+850', code: 'KP', emoji: '🇰🇵' },
  { name: 'Hong Kong', dial: '+852', code: 'HK', emoji: '🇭🇰' },
  { name: 'Macau', dial: '+853', code: 'MO', emoji: '🇲🇴' },
  { name: 'Cambodia', dial: '+855', code: 'KH', emoji: '🇰🇭' },
  { name: 'Laos', dial: '+856', code: 'LA', emoji: '🇱🇦' },
  { name: 'Bangladesh', dial: '+880', code: 'BD', emoji: '🇧🇩' },
  { name: 'Taiwan', dial: '+886', code: 'TW', emoji: '🇹🇼' },
  { name: 'Maldives', dial: '+960', code: 'MV', emoji: '🇲🇻' },
  { name: 'Lebanon', dial: '+961', code: 'LB', emoji: '🇱🇧' },
  { name: 'Jordan', dial: '+962', code: 'JO', emoji: '🇯🇴' },
  { name: 'Syria', dial: '+963', code: 'SY', emoji: '🇸🇾' },
  { name: 'Iraq', dial: '+964', code: 'IQ', emoji: '🇮🇶' },
  { name: 'Kuwait', dial: '+965', code: 'KW', emoji: '🇰🇼' },
  { name: 'Saudi Arabia', dial: '+966', code: 'SA', emoji: '🇸🇦' },
  { name: 'Yemen', dial: '+967', code: 'YE', emoji: '🇾🇪' },
  { name: 'Oman', dial: '+968', code: 'OM', emoji: '🇴🇲' },
  { name: 'Palestine', dial: '+970', code: 'PS', emoji: '🇵🇸' },
  { name: 'United Arab Emirates', dial: '+971', code: 'AE', emoji: '🇦🇪' },
  { name: 'Israel', dial: '+972', code: 'IL', emoji: '🇮🇱' },
  { name: 'Bahrain', dial: '+973', code: 'BH', emoji: '🇧🇭' },
  { name: 'Qatar', dial: '+974', code: 'QA', emoji: '🇶🇦' },
  { name: 'Bhutan', dial: '+975', code: 'BT', emoji: '🇧🇹' },
  { name: 'Mongolia', dial: '+976', code: 'MN', emoji: '🇲🇳' },
  { name: 'Nepal', dial: '+977', code: 'NP', emoji: '🇳🇵' },
  { name: 'Tajikistan', dial: '+992', code: 'TJ', emoji: '🇹🇯' },
  { name: 'Turkmenistan', dial: '+993', code: 'TM', emoji: '🇹🇲' },
  { name: 'Azerbaijan', dial: '+994', code: 'AZ', emoji: '🇦🇿' },
  { name: 'Georgia', dial: '+995', code: 'GE', emoji: '🇬🇪' },
  { name: 'Kyrgyzstan', dial: '+996', code: 'KG', emoji: '🇰🇬' },
  { name: 'Uzbekistan', dial: '+998', code: 'UZ', emoji: '🇺🇿' },
  { name: 'Bahamas', dial: '+1-242', code: 'BS', emoji: '🇧🇸' },
  { name: 'Barbados', dial: '+1-246', code: 'BB', emoji: '🇧🇧' },
  { name: 'Anguilla', dial: '+1-264', code: 'AI', emoji: '🇦🇮' },
  { name: 'Antigua and Barbuda', dial: '+1-268', code: 'AG', emoji: '🇦🇬' },
  { name: 'British Virgin Islands', dial: '+1-284', code: 'VG', emoji: '🇻🇬' },
  { name: 'U.S. Virgin Islands', dial: '+1-340', code: 'VI', emoji: '🇻🇮' },
  { name: 'Cayman Islands', dial: '+1-345', code: 'KY', emoji: '🇰🇾' },
  { name: 'Bermuda', dial: '+1-441', code: 'BM', emoji: '🇧🇲' },
  { name: 'Grenada', dial: '+1-473', code: 'GD', emoji: '🇬🇩' },
  { name: 'Turks and Caicos Islands', dial: '+1-649', code: 'TC', emoji: '🇹🇨' },
  { name: 'Montserrat', dial: '+1-664', code: 'MS', emoji: '🇲🇸' },
  { name: 'Sint Maarten', dial: '+1-721', code: 'SX', emoji: '🇸🇽' },
  { name: 'Saint Lucia', dial: '+1-758', code: 'LC', emoji: '🇱🇨' },
  { name: 'Dominica', dial: '+1-767', code: 'DM', emoji: '🇩🇲' },
  { name: 'Saint Vincent and the Grenadines', dial: '+1-784', code: 'VC', emoji: '🇻🇨' },
  { name: 'Dominican Republic', dial: '+1-809', code: 'DO', emoji: '🇩🇴' },
  { name: 'Trinidad and Tobago', dial: '+1-868', code: 'TT', emoji: '🇹🇹' },
  { name: 'Saint Kitts and Nevis', dial: '+1-869', code: 'KN', emoji: '🇰🇳' },
  { name: 'Jamaica', dial: '+1-876', code: 'JM', emoji: '🇯🇲' },
  { name: 'Puerto Rico', dial: '+1-939', code: 'PR', emoji: '🇵🇷' },
].map(country => ({ ...country, flag: getFlagUrl(country.code) })) as Country[];
