// Auto-generated from assets/selection.json
// Enum maps sanitized keys to IcoMoon glyph names

export enum IconName {
    Property1Apple = 'Property-1Apple',
    Property1ArrowDown = 'Property-1Arrow-down',
    Property1ArrowLeft = 'Property-1Arrow-left',
    Property1ArrowReceive = 'Property-1Arrow-Receive',
    Property1ArrowRight = 'Property-1Arrow-right',
    Property1ArrowSend = 'Property-1Arrow-Send',
    Property1ArrowUp = 'Property-1Arrow-up',
    Property1ATMCard = 'Property-1ATM-Card',
    Property1Bank = 'Property-1Bank',
    Property1CardOutline = 'Property-1Card-Outline',
    Property1Card = 'Property-1Card',
    Property1ChartOutline = 'Property-1Chart-Outline',
    Property1Chart = 'Property-1Chart',
    Property1CurrencyDollar = 'Property-1Currency-Dollar',
    Property1Delete = 'Property-1Delete',
    Property1Doc = 'Property-1Doc',
    Property1Euro = 'Property-1Euro',
    Property1EyeOpen = 'Property-1Eye-open',
    Property1FaceRecognition = 'Property-1Face-Recognition',
    Property1FingerPrint = 'Property-1Finger-Print',
    Property1Google = 'Property-1Google',
    Property1Help = 'Property-1Help',
    Property1History = 'Property-1History',
    Property1LearnOutline = 'Property-1Learn-outline',
    Property1Learn = 'Property-1Learn',
    Property1Location = 'Property-1Location',
    Property1Message = 'Property-1Message',
    Property1Notification = 'Property-1Notification',
    Property1Padlock = 'Property-1padlock',
    Property1Phone = 'Property-1Phone',
    Property1Plus = 'Property-1Plus',
    Property1RampaOutline = 'Property-1Rampa-Outline',
    Property1RampaSolid = 'Property-1Rampa-Solid',
    Property1Report = 'Property-1Report',
    Property1Search = 'Property-1Search',
    Property1Send = 'Property-1Send',
    Property1Theme = 'Property-1Theme',
    Property1Variant25 = 'Property-1Variant25',
    Property1Verify = 'Property-1Verify',
    Property1Wallet = 'Property-1Wallet',
    Vector = 'Vector',
    Usdc = 'USDC',
}

export type IconNameKeys = `${IconName}`;

